# Generated by Django 6.1 on 2026-08-20 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='descipcion',
            new_name='descripcion',
        ),
    ]
